name: Upload to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: "projects/919227918560/locations/global/workloadIdentityPools/github/providers/mam29"
          service_account: "my-service-account@staticsite-419218.iam.gserviceaccount.com"

      - name: Upload file to Google Cloud Storage
        run: gsutil cp ./HTML/website.html gs://web-bucket-0

       # upload files to GCS
      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'HTML'
          destination: 'web-bucket-0'
          parent: false
